-- ==============================================================================
-- Telemt WEB Proxy CBI model
-- Telemt >= 3.5.6
-- UCI /etc/config/telemt remains the single source of truth.
-- ==============================================================================

local sys = require "luci.sys"
local uci = require("luci.model.uci").cursor()

local function trim(s)
    return (tostring(s or ""):gsub("^%s+", ""):gsub("%s+$", ""))
end

local function html_escape(s)
    return tostring(s or "")
        :gsub("&", "&amp;")
        :gsub("<", "&lt;")
        :gsub(">", "&gt;")
        :gsub('"', "&quot;")
end

local function valid_vhost_name(v)
    return v:match("^[A-Za-z0-9_-]+$") ~= nil
end

local function valid_fqdn(v)
    if #v < 3 or #v > 253 or not v:find("%.", 1, false) then return false end
    if not v:match("^[A-Za-z0-9][A-Za-z0-9%.%-]*[A-Za-z0-9]$") then return false end
    if v:find("%.%.", 1, false) then return false end
    for label in v:gmatch("[^%.]+") do
        if #label > 63 or label:sub(1,1) == "-" or label:sub(-1) == "-" then return false end
    end
    return true
end

local function valid_public_addr(v)
    if v:match("^%d+%.%d+%.%d+%.%d+:443$") then return true end
    if v:match("^%[[0-9A-Fa-f:]+%]:443$") then return true end
    return false
end

local function valid_decoy(v)
    if v:match("^http://%d+%.%d+%.%d+%.%d+:%d+$") then return true end
    if v:match("^http://%d+%.%d+%.%d+%.%d+$") then return true end
    if v:match("^http://%[[0-9A-Fa-f:]+%]:%d+$") then return true end
    if v:match("^http://%[[0-9A-Fa-f:]+%]$") then return true end
    return false
end

local function helper_output(path, arg)
    if sys.call("test -x " .. path .. " >/dev/null 2>&1") ~= 0 then
        return "helper missing: " .. path
    end
    return trim(sys.exec(path .. " " .. arg .. " 2>&1") or "")
end

local users = {}
uci:foreach("telemt", "user", function(s)
    local name = s[".name"]
    if name and name ~= "" then
        users[#users + 1] = {
            name = name,
            enabled = tostring(s.enabled or "1") ~= "0"
        }
    end
end)
table.sort(users, function(a, b) return a.name < b.name end)

local vhosts = {}
uci:foreach("telemt", "web_vhost", function(s)
    local name = trim(s.name or "")
    if name ~= "" then vhosts[#vhosts + 1] = name end
end)
table.sort(vhosts)

m = Map("telemt", _("Telemt WEB Proxy"),
    _("WEB Proxy support for Telemt 3.5.6+. Configuration is stored only in /etc/config/telemt; the runtime TOML is generated by /etc/init.d/telemt."))

-- -----------------------------------------------------------------------------
-- Read-only runtime summary
-- -----------------------------------------------------------------------------
status = m:section(SimpleSection)
status.title = _("WEB status")
status.description = _("Read-only state from the core helper. Save & Apply configuration changes before relying on this status.")

st = status:option(DummyValue, "_status")
st.rawhtml = true
function st.cfgvalue()
    local out = helper_output("/usr/libexec/telemt-web-check", "")
    return "<pre style='white-space:pre-wrap;margin:0'>" .. html_escape(out) .. "</pre>"
end

-- -----------------------------------------------------------------------------
-- Global WEB settings
-- -----------------------------------------------------------------------------
web = m:section(NamedSection, "web", "web", _("WEB Proxy"))
web.addremove = false
web.anonymous = true

enabled = web:option(Flag, "enabled", _("Enable WEB Proxy"))
enabled.rmempty = false
enabled.default = enabled.disabled
enabled.description = _("WEB remains disabled on upgrade until explicitly enabled.")

carrier = web:option(ListValue, "carrier", _("Carrier"))
carrier:value("https", "HTTPS")
carrier.default = "https"
carrier.rmempty = false
carrier.description = _("The first WEB UI stage intentionally exposes only the conservative HTTPS carrier. Lanes/WebSocket modes will be added after hardware testing.")

frontend = web:option(ListValue, "tls_terminator", _("TLS frontend"))
frontend:value("external", _("External / already configured"))
frontend:value("haproxy", _("HAProxy"))
frontend.default = "external"
frontend.rmempty = false
frontend.description = _("Telemt WEB listens for private plain HTTP. Public TLS must terminate before it reaches Telemt.")

hm = web:option(Flag, "haproxy_managed", _("Manage HAProxy configuration"))
hm:depends("tls_terminator", "haproxy")
hm.default = hm.disabled
hm.rmempty = false
hm.description = _("Opt-in takeover of /etc/haproxy.cfg. The core helper saves the original once and validates generated configuration with haproxy -c before replacing it.")

hb = web:option(Value, "haproxy_bind", _("HAProxy public bind"))
hb:depends({ tls_terminator = "haproxy", haproxy_managed = "1" })
hb.default = ":443"
hb.placeholder = ":443"
hb.rmempty = false
hb.description = _("TCP/443 only, for example :443, 0.0.0.0:443 or [::]:443. Existing uhttpd/NGINX listeners must be resolved first.")
function hb.validate(self, value, section)
    value = trim(value)
    if value == ":443" or value == "0.0.0.0:443" or value:match("^%d+%.%d+%.%d+%.%d+:443$") or value:match("^%[[0-9A-Fa-f:]+%]:443$") then
        return value
    end
    return nil, _("HAProxy bind must be an address on TCP/443")
end

hc = web:option(Value, "haproxy_cert", _("Certificate / fullchain PEM"))
hc:depends({ tls_terminator = "haproxy", haproxy_managed = "1" })
hc.placeholder = "/etc/acme/example/fullchain.cer"
hc.rmempty = true
hc.description = _("If the PEM already contains the private key, leave the key field empty.")

hk = web:option(Value, "haproxy_key", _("Private key"))
hk:depends({ tls_terminator = "haproxy", haproxy_managed = "1" })
hk.placeholder = "/etc/acme/example/example.key"
hk.rmempty = true

hfw = web:option(Flag, "haproxy_auto_fw", _("Open WAN TCP/443 after successful apply"))
hfw:depends({ tls_terminator = "haproxy", haproxy_managed = "1" })
hfw.default = hfw.enabled
hfw.rmempty = false
hfw.description = _("The private Telemt backend port is never opened by this option.")

-- -----------------------------------------------------------------------------
-- Private WEB listener
-- -----------------------------------------------------------------------------
listener = m:section(NamedSection, "web_listener", "web_listener", _("Private WEB backend"))
listener.addremove = false
listener.anonymous = true

le = listener:option(Flag, "enabled", _("Enable backend listener"))
le.default = le.enabled
le.rmempty = false

lip = listener:option(Value, "ip", _("Listen address"))
lip.default = "127.0.0.1"
lip.placeholder = "127.0.0.1"
lip.rmempty = false
lip.description = _("Managed HAProxy requires 127.0.0.1. External frontends may use another private address when required.")

lp = listener:option(Value, "port", _("Listen port"))
lp.datatype = "port"
lp.default = "27453"
lp.placeholder = "27453"
lp.rmempty = false
lp.description = _("Default 27453 avoids common local proxy ports such as 18080.")

xff = listener:option(ListValue, "client_ip_source", _("Client IP source"))
xff:value("x_forwarded_for", "X-Forwarded-For")
xff.default = "x_forwarded_for"
xff.rmempty = false

trusted = listener:option(DynamicList, "trusted_proxy_cidr", _("Trusted frontend CIDRs"))
trusted.default = "127.0.0.1/32"
trusted.placeholder = "127.0.0.1/32"
trusted.rmempty = false
trusted.description = _("Only immediate TLS frontend peers belong here. /0 is forbidden by the core generator.")

-- -----------------------------------------------------------------------------
-- VHosts
-- -----------------------------------------------------------------------------
vh = m:section(TypedSection, "web_vhost", _("WEB virtual hosts"),
    _("Each enabled public hostname maps to one Telemt WEB vhost. public_addr is the concrete public IP on :443; the decoy is currently an HTTP IP-literal origin."))
vh.template = "cbi/tblsection"
vh.anonymous = true
vh.addremove = true
vh.sortable = true

vhe = vh:option(Flag, "enabled", _("On"))
vhe.default = vhe.enabled
vhe.rmempty = false

vhn = vh:option(Value, "name", _("Name"))
vhn.rmempty = false
vhn.placeholder = "main"
function vhn.validate(self, value, section)
    value = trim(value)
    if valid_vhost_name(value) then return value end
    return nil, _("Use only A-Z, a-z, 0-9, underscore and hyphen")
end

vhh = vh:option(Value, "host", _("Public host"))
vhh.rmempty = false
vhh.placeholder = "proxy.example.com"
function vhh.validate(self, value, section)
    value = trim(value):lower()
    if valid_fqdn(value) then return value end
    return nil, _("Enter a valid FQDN")
end

vhp = vh:option(Value, "public_addr", _("Public address"))
vhp.rmempty = false
vhp.placeholder = "203.0.113.10:443"
function vhp.validate(self, value, section)
    value = trim(value)
    if valid_public_addr(value) then return value end
    return nil, _("Use a concrete IPv4 or [IPv6] address on :443")
end

vhd = vh:option(Value, "decoy_upstream", _("HTTP decoy"))
vhd.rmempty = false
vhd.placeholder = "http://127.0.0.1:27454"
vhd.description = _("Current LAB supports http_upstream only: http://IP[:port], without path/query/credentials.")
function vhd.validate(self, value, section)
    value = trim(value)
    if valid_decoy(value) then return value end
    return nil, _("Use http://IP[:port] without path or query")
end

-- decoy_mode is currently fixed by the core implementation; keep it in UCI but
-- do not make the user choose a value which cannot work yet.
function vh.create(self, section)
    local sid = TypedSection.create(self, section)
    if sid then uci:set("telemt", sid, "decoy_mode", "http_upstream") end
    return sid
end

-- -----------------------------------------------------------------------------
-- Profiles -> shared config user
-- -----------------------------------------------------------------------------
pr = m:section(TypedSection, "web_profile", _("WEB profiles"),
    _("A WEB profile binds a vhost to an existing Telemt user. Secrets, quota, expiration and enabled state remain exclusively in the shared Users database."))
pr.template = "cbi/tblsection"
pr.anonymous = true
pr.addremove = true
pr.sortable = true

pre = pr:option(Flag, "enabled", _("On"))
pre.default = pre.enabled
pre.rmempty = false

prv = pr:option(Value, "vhost", _("VHost"))
prv.rmempty = false
prv.placeholder = "main"
for _, name in ipairs(vhosts) do prv:value(name, name) end
function prv.validate(self, value, section)
    value = trim(value)
    if valid_vhost_name(value) then return value end
    return nil, _("Enter the Name of an enabled WEB vhost")
end

pru = pr:option(ListValue, "user", _("Shared user"))
pru.rmempty = false
if #users == 0 then
    pru:value("", _("No Telemt users configured"))
else
    for _, item in ipairs(users) do
        local label = item.name
        if not item.enabled then label = label .. " (disabled)" end
        pru:value(item.name, label)
    end
end
pru.description = _("The secret is read from config user; it is never copied into the WEB profile.")

prm = pr:option(ListValue, "secret_mode", _("WEB secret mode"))
prm:value("dd", "DD")
prm:value("plain", _("Plain"))
prm.default = "dd"
prm.rmempty = false

pms = pr:option(Value, "max_sessions", _("Max sessions"))
pms.datatype = "uinteger"
pms.rmempty = true
pms.placeholder = _("core default")

pmst = pr:option(Value, "max_streams", _("Max streams"))
pmst.datatype = "uinteger"
pmst.rmempty = true
pmst.placeholder = _("core default")

pmss = pr:option(Value, "max_streams_per_session", _("Streams/session"))
pmss.datatype = "uinteger"
pmss.rmempty = true
pmss.placeholder = _("core default")

-- -----------------------------------------------------------------------------
-- Frontend read-only state. Mutating Check/Apply/Restore buttons are deliberately
-- added in a separate patch so their CBI commit ordering cannot race Save & Apply.
-- -----------------------------------------------------------------------------
frontst = m:section(SimpleSection)
frontst.title = _("HAProxy helper state")
frontst.description = _("Read-only. Managed actions will be exposed after the page configuration path is validated on LuCI 21.02-25.x.")

fsv = frontst:option(DummyValue, "_frontend_status")
fsv.rawhtml = true
function fsv.cfgvalue()
    local out = helper_output("/usr/libexec/telemt-web-frontend", "status")
    return "<pre style='white-space:pre-wrap;margin:0'>" .. html_escape(out) .. "</pre>"
end

return m
